# Generated by Django 4.1.5 on 2026-03-13 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0002_symptomonset_medicationhistory_allergyhistory"),
        ("lab_report", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="labreport",
            name="identity_meta",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Extracted patient demographics: name, age, sex, IDs",
            ),
        ),
        migrations.AddField(
            model_name="labreport",
            name="profile_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="PatientProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(default="My Health", max_length=100)),
                ("patient_name", models.CharField(blank=True, max_length=200)),
                ("age", models.IntegerField(blank=True, null=True)),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female"), ("Other", "Other")],
                        max_length=10,
                    ),
                ),
                (
                    "external_ids",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores SRF_ID, UHID, MRN, etc. as key-value pairs",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_profiles",
                        to="user_profile.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": "patient_profiles",
                "ordering": ["-updated_at"],
                "unique_together": {("user_profile", "label")},
            },
        ),
        migrations.CreateModel(
            name="BiomarkerSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(blank=True, null=True)),
                (
                    "biomarkers_json",
                    models.JSONField(
                        default=list,
                        help_text="Full structured biomarker array from LLM extraction",
                    ),
                ),
                ("abnormal_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lab_report",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="biomarker_snapshot",
                        to="lab_report.labreport",
                    ),
                ),
                (
                    "patient_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="biomarker_snapshots",
                        to="lab_report.patientprofile",
                    ),
                ),
            ],
            options={
                "db_table": "biomarker_snapshots",
                "ordering": ["-report_date", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="labreport",
            name="patient_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lab_reports",
                to="lab_report.patientprofile",
            ),
        ),
    ]
