# Generated by Django 4.2.4 on 2026-02-22 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SymptomOnset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symptom_description", models.CharField(max_length=300)),
                ("body_system", models.CharField(max_length=100)),
                ("onset_date", models.DateTimeField()),
                (
                    "severity_at_onset",
                    models.IntegerField(
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                        ]
                    ),
                ),
                (
                    "current_severity",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                        ],
                        null=True,
                    ),
                ),
                ("duration_days", models.IntegerField(blank=True, null=True)),
                ("is_chronic", models.BooleanField(default=False)),
                (
                    "pattern",
                    models.CharField(
                        choices=[
                            ("constant", "Constant"),
                            ("intermittent", "Intermittent"),
                            ("worsening", "Worsening"),
                            ("improving", "Improving"),
                            ("fluctuating", "Fluctuating"),
                        ],
                        max_length=50,
                    ),
                ),
                ("associated_conditions", models.TextField(blank=True)),
                ("medications_tried", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="symptom_onsets",
                        to="user_profile.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": "symptom_onsets",
                "ordering": ["-onset_date"],
            },
        ),
        migrations.CreateModel(
            name="MedicationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medication_name", models.CharField(db_index=True, max_length=200)),
                ("generic_name", models.CharField(blank=True, max_length=200)),
                ("dosage", models.CharField(max_length=100)),
                ("frequency", models.CharField(max_length=100)),
                ("route", models.CharField(default="oral", max_length=50)),
                ("start_date", models.DateTimeField()),
                ("stop_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("discontinued", "Discontinued"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("prescribed_by", models.CharField(blank=True, max_length=200)),
                ("reason_for_taking", models.TextField(blank=True)),
                ("reason_for_discontinuation", models.TextField(blank=True)),
                ("side_effects_experienced", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medication_history",
                        to="user_profile.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": "medication_history",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="AllergyHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allergen", models.CharField(db_index=True, max_length=200)),
                (
                    "allergen_type",
                    models.CharField(
                        choices=[
                            ("food", "Food"),
                            ("medication", "Medication"),
                            ("herb", "Herb/Supplement"),
                            ("environmental", "Environmental"),
                            ("latex", "Latex"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("mild", "Mild"),
                            ("moderate", "Moderate"),
                            ("severe", "Severe"),
                            ("life_threatening", "Life-Threatening"),
                        ],
                        max_length=20,
                    ),
                ),
                ("onset_date", models.DateField(blank=True, null=True)),
                ("first_reaction_date", models.DateField(blank=True, null=True)),
                ("symptoms", models.TextField()),
                ("testing_method", models.CharField(blank=True, max_length=100)),
                ("confirmed_by_testing", models.BooleanField(default=False)),
                ("cross_reactive_allergens", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allergy_history",
                        to="user_profile.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": "allergy_history",
                "ordering": ["-onset_date", "-created_at"],
            },
        ),
    ]
