# Generated by Django 4.2.4 on 2025-11-21 07:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                ("allergies", models.TextField(blank=True, null=True)),
                ("medical_conditions", models.TextField(blank=True, null=True)),
                ("current_medications", models.TextField(blank=True, null=True)),
                ("is_profile_complete", models.BooleanField(default=False)),
                ("profile_completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_login", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "user_profiles",
                "ordering": ["-created_at"],
            },
        ),
    ]
